### ISSUE TITLE
Rolling

### ISSUE THREAD

**Issue by Kyazoo** [RPDND-Development/IssueTracker#2]
![image](https://user-images.githubusercontent.com/91627313/224195636-708dbf05-7dfe-4fcc-9dcf-c80a0bd86208.png)
Color Text isnt showing.

Make DMrolling available for all players (so they can private roll but only where they can see the result/rolls)
Normal rolling can be public to everyone.

Also is there a way to get the results to be posted in console?

**Comment by ShreyasAyyengar** [comment]
Implemented.
