### ISSUE TITLE
Chat Plugin

### ISSUE THREAD

**Issue by Kyazoo** [RPDND-Development/IssueTracker#3]
Reduce Objsdjfhskdjhfs distance.

Shout - last five blocks or less.
Quiet/Whisper - None
Local/RP - last 1-2 blocks
OOC - none

Reduce how many letters it actually removes or % replaced by hyphens.

![image](https://user-images.githubusercontent.com/91627313/224195736-09ac7d79-112a-4544-87b4-120dfd507dc9.png)

**Comment by ShreyasAyyengar** [comment]
Consider switching the replacement character to something else?
